[project]
name = "fluentpython"
version = "0.1.0"
description = "Study Fluent Python"
authors = [{name = "chen", email = "chldnjsdnd12@gmail.com"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
